name: Deploy to Server

on: 
  workflow_dispatch:
  push:
    branches:
      - master  # Utilisez votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  #   - name: ping
  #     run: |
  #         echo "Testing ping to baudelot.alwaysdata.net..."
  #         ping -c 4 baudelot.alwaysdata.net || exit 1
          
    - name: Check SSH port 22 accessibility
      run: |
          echo "Testing SSH port 22 accessibility..."
          nc -zv baudelot.alwaysdata.net 22 || exit 1
    
    - name: Setup SSH
      run: |
        # Assurez-vous que le répertoire ~/.ssh existe
        mkdir -p ~/.ssh
        # Écrit la clé privée à partir des secrets (si nécessaire)
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Ajoute le serveur Alwaysdata à known_hosts en forçant l'IPv4
        ssh-keyscan -4 -H baudelot.alwaysdata.net >> ~/.ssh/known_hosts

    - name: Deploy code via SSH
      run: |
        # Se connecte à Alwaysdata et déploie le code en forçant l'IPv4
        ssh -4 -i ~/.ssh/id_rsa baudelot@ssh-baudelot.alwaysdata.net "cd /home/baudelot && git pull"

